server:
  port: 8003

mybatis:
  type-aliases-package: com.mudaxian.springcloud.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml
#  config-location: classpath:mybatis/mybatis-config.xml

spring:
  application:
    name: springcloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/study3?useSSL=true&useUnicode=true&characterEnding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/,http://127.0.0.1:7002/eureka/
  instance:
    instance-id: springcloud-provider-dept8003

info:
  app.name: 牟文豪
  company.name: mudaxian