server:
  port: 7003

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false #表示是否想eureka注册中心注册自己
    fetch-registry: false #fetch-registry如果为false，则表示自己为注册中心
    service-url:
      defaultZone: http://${eureka.instance.hostname}:7001/eureka/,http://${eureka.instance.hostname}:7002/eureka/